"""Initial revision

Revision ID: bc09c788e108
Revises: 
Create Date: 2025-02-26 15:55:24.537592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc09c788e108'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pastes',
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('hashid', sa.String(), nullable=False),
    sa.Column('start_life', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_life', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pastes_hashid'), 'pastes', ['hashid'], unique=True)
    op.create_index(op.f('ix_pastes_text'), 'pastes', ['text'], unique=False)
    op.create_index(op.f('ix_pastes_url'), 'pastes', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pastes_url'), table_name='pastes')
    op.drop_index(op.f('ix_pastes_text'), table_name='pastes')
    op.drop_index(op.f('ix_pastes_hashid'), table_name='pastes')
    op.drop_table('pastes')
    # ### end Alembic commands ###
